### ISSUE TITLE
Unable to create foxtrot cluster

### ISSUE THREAD

**Issue by anhat** [Flipkart/foxtrot#100]
Whats the use of following settings in local.yml ?
cluster:
  name: foxtrot
  disableMulticast: true
  members: ["localhost:5701", "localhost:5702"]

I have tested stand-alone foxtrot instances but unable to create a cluster of them. Any specific settings needed ?

**Comment by santanusinha** [comment]
This is used to form the cluster. 

Replace localhost etc with ips of your machines running foxtrot.

**Comment by santanusinha** [comment]
Also if you are setting up a new instance, please use 0.3 branch.

**Comment by santanusinha** [comment]
Closing this. Please reopen if this if you're still finding issues.
