### ISSUE TITLE
foxtrot docker: local es setup script issue

### ISSUE THREAD

**Issue by vivekkothari** [Flipkart/foxtrot#101]
the local_es_setup.sh script disables the _source thus nothing comes up on the console. The _source should no be disabled.

**Comment by r0goyal** [comment]
@vivekkothari Please further explain where in console nothing is showing up. disabling _source is by design and raw data is stored in HBase which is used when using filters on console.

**Comment by vivekkothari** [comment]
Issue:
I created a non-seggregated table say "table1". Then I post a document to it. In elasticsearch it is indexed. Now from console, I select "table1" and then I click on the search icon. I don't see any records. 

Now when I change the template to enable _source and repeat the similar steps, i see the indexed document, so it seems that console is not getting the data from HBase and only from elasticsearch.

**Comment by sgmarghade** [comment]
@vivekkothari this was due to bug recently got pushed in script if u run script explicitly (Not required in docker). 
Have raised pull request for the same. For time being in ur local_es_script replace 

"template" : "${2}-*"
    with 
"template" : "'${2}'-*"
