### ISSUE TITLE
Wiki enhancement.

### ISSUE THREAD

**Issue by sgmarghade** [Flipkart/foxtrot#108]
Can we add following points to wiki .
1. How to create dashboard and use them with filters and values. 
2. No direct link to "Filters" in wiki's right navigation pane.  (https://github.com/Flipkart/foxtrot/wiki/Filters) , for quick reference. 
3. Missing wiki for https://github.com/Flipkart/foxtrot/wiki/Event-Counts

**Comment by santanusinha** [comment]
4. Docker based setup
5. Data model

**Comment by sgmarghade** [comment]
1. Possible use case of using Foxtrot. (For someone/beginner where can we use it or How flipkart is using it)

**Comment by sgmarghade** [comment]
Filters for following missing in wiki : 

String in = "in";
String exists = "exists";
String missing = "missing"

**Comment by anistark** [comment]
:+1:  @sgmarghade

**Comment by nitishgoyal13** [comment]
1. Event-Count API is added : https://github.com/Flipkart/foxtrot/wiki/Event-Count
2. Filter API is added : https://github.com/Flipkart/foxtrot/wiki/Filters

**Comment by nitishgoyal13** [comment]
> Filters for following missing in wiki :
> 
> String in = "in";
> String exists = "exists";
> String missing = "missing"

All the above filters are added
