### ISSUE TITLE
Metrics aggregation support in group aggregation.

### ISSUE THREAD

**Issue by sgmarghade** [Flipkart/foxtrot#109]
Currently we support only term aggregation type, which is bucket aggregation. We can also have metrics aggregation as specified by user. 

Use case :- document has hub_id, agent_id , amount. currently group returns only count of documents at agent_id level and to get sum or avg of amount we have to use stats api for each agent_id . 

We can have similar feature as innermost aggregation in group aggregation. This will return document count for each agent_id inside hub_id also sum / avg / stats/ min / max of field specified by user for each agent_id.

**Comment by r0goyal** [comment]
@sgmarghade Santanu ( @santanusinha ) is already working on this.

**Comment by sgmarghade** [comment]
Ohhhh nice.. thanks.

**Comment by r0goyal** [comment]
@sgmarghade This is implemented by #169
