### ISSUE TITLE
Concept of admin/co-ordinator node

### ISSUE THREAD

**Issue by r0goyal** [Flipkart/foxtrot#114]
Today in foxtrot, deletion of indexes is done by node which is configured through configuration. However this is not the best approach since this node can go down at any point of time, leaving cluster with excess of data.

Also, in future there would be multiple tasks which needs to be managed centrally (example - #80).

**Comment by santanusinha** [comment]
Along with this, let's also add the concept of running a node only as a
query node. Should be trivial.

**Comment by santanusinha** [comment]
Query and UI .. I mean.

----
Upset the established order, and everything becomes chaos. I'm an agent of
chaos. Oh and you know the thing about chaos, it's fair.

**Comment by sgmarghade** [comment]
Can we proxy cluster stats calls through foxtrot server ? Currently it works if there is direct access to cluster nodes which may not be the case if someone wants to expose console URL outside network.

**Comment by nitishgoyal13** [comment]
This one is fixed
