### ISSUE TITLE
Moving Cluster API to Foxtrot server

### ISSUE THREAD

**Issue by sgmarghade** [Flipkart/foxtrot#115]
Can we proxy cluster stats calls through foxtrot server ? Currently it works if there is direct access to cluster nodes which may not be the case if someone wants to expose console URL outside network.

**Comment by santanusinha** [comment]
Good idea.. Maybe use a simplified model as well.. Patch please.. :-P

**Comment by sgmarghade** [comment]
Will give it a shot =D

**Comment by r0goyal** [comment]
Closed by #116
