### ISSUE TITLE
Not able to delete a console

### ISSUE THREAD

**Issue by arifmrn** [Flipkart/foxtrot#127]
Created multiple consoles for a table. Now couldn't delete the console which i created. Tried sending a delete request with console name but isnt working. Please help

**Comment by r0goyal** [comment]
@arifmrn Are you getting any exception ?

**Comment by arifmrn** [comment]
@r0goyal : No I am not getting any exception. But what is the procedure to delete a console ? . I dont see anything in the UI to do the same. And no documentation abt it :( . I tried sending a delete request via postman client and even that didnt work. So whats the way to delete it.

**Comment by r0goyal** [comment]
@arifmrn API endpoint for deleting console is **/v1/consoles/{id}/delete** with HttpMethod DELETE. Currently there is no way to delete console from UI. Please create a feature request for that. Agreed that there is no documentation regarding console API. Please create another issue for that. Will work actively towards creating it

**Comment by arifmrn** [comment]
@r0goyal : Sure will do. Thanks a lot for the quick turnaround

**Comment by arifmrn** [comment]
@r0goyal : "API endpoint for deleting console is /v1/consoles/{id}/delete ". This is not working!!. Still not able to delete console :(

**Comment by nitishgoyal13** [comment]
API is working
Will see if we need to add this in UI

**Comment by nitishgoyal13** [comment]
Merging it with
https://github.com/Flipkart/foxtrot/issues/129
