### ISSUE TITLE
Can a not_contains filter be added in the console ?

### ISSUE THREAD

**Issue by rajatflipkart** [Flipkart/foxtrot#144]
It would enhance the filtering . Currently unable to filter out unwanted noise.

**Comment by santanusinha** [comment]
Filters can be configures in the filter section. Apologies for the lack of documentation. Filters currently accept a json of the form:

```
{
    "filters": [
        {
            "field": "some_field",
            "operator": "not_equals",
            "value": "A"
        },
        {
            "field": "some_field",
            "operator": "not_equals",
            "value": "B"
        }
    ]
}
```

**Comment by rajatflipkart** [comment]
Clarification : This is for browsing events. Just like contains filters events which have a substring, A not_contains filter will remove the events which dont have a substring.
<img width="1208" alt="screen shot 2016-05-13 at 4 45 58 pm" src="https://cloud.githubusercontent.com/assets/8060535/15246555/4fb15c3a-192b-11e6-8fd3-dec411886a79.png">

ps: documentation for filters is available here : https://github.com/Flipkart/foxtrot/wiki/Filters.
It would be useful to have a not_contains filter here.

**Comment by nitishgoyal13** [comment]
Will add In and Not In filter to support this feature

**Comment by nitishgoyal13** [comment]
Not In filter can now be selected
#240
