### ISSUE TITLE
Add a feature to allow comparison of data.

### ISSUE THREAD

**Issue by hardikdosi** [Flipkart/foxtrot#157]
- There is no tile available which allows to compare today's data with previous day data. 
- Bar Chart and Histogram can be used to present such a comparison.
- It would be a nice enhancement to have.

**Comment by santanusinha** [comment]
Agreed. This is actually a long pending feature. Will try to take this up
for 0.5 itself.

**Comment by hardikdosi** [comment]
Would be glad to pick it up. Will share implementation details soon.

**Comment by nitishgoyal13** [comment]
Fixed and merged
