### ISSUE TITLE
Adding new data visualisation tools like adding time range and data aggregation filters.

### ISSUE THREAD

**Issue by banasumit** [Flipkart/foxtrot#159]
<img width="1163" alt="70fb258a7acdb94386624af952618313" src="https://cloud.githubusercontent.com/assets/19607262/16226225/0d85a7ec-37c8-11e6-9e93-57ccb066a3d8.png">
<img width="378" alt="e53e481bd1808f8251b5dddc88445357" src="https://cloud.githubusercontent.com/assets/19607262/16226301/64174002-37c8-11e6-9fc4-ea2bb1ab3a89.png">

**Comment by nitishgoyal13** [comment]
Adding a date picker in the filters 
User can select the field and date value from the picker
