### ISSUE TITLE
Deletion task times out for large indices

### ISSUE THREAD

**Issue by avanishp** [Flipkart/foxtrot#161]
The deletion task times out for larger indices and those remain to be in the system even though they should be deleted from ES. 

Can we change the timeout to a higher value or set the sublist of lesser size. Will there be any impact because of that?
<img width="806" alt="screen shot 2016-06-21 at 7 52 28 pm" src="https://cloud.githubusercontent.com/assets/12965519/16232852/b76dc1ba-37e9-11e6-93b2-3c4b3e39fdf0.png">

**Comment by nitishgoyal13** [comment]
Haven't observed this issue. Hence, closing the ticket
