### ISSUE TITLE
Add UI tile for enabling multi level grouping visualization

### ISSUE THREAD

**Issue by r0goyal** [Flipkart/foxtrot#164]
Currently, pie and bar charts allow only one level of nesting. There are many scenarios where multilevel grouping needs to be visualized. Potential options of charts can be - 

Sunburst - http://bl.ocks.org/kerryrodden/7090426
Dendogram - https://bl.ocks.org/mbostock/4339083

**Comment by santanusinha** [comment]
D3 is heavy and putting it in a dynamically refresing widget tile will kill the performance. We should ideally introduce a new section for analytics and put in visualizations like this in there.

**Comment by r0goyal** [comment]
Agreed. This can be another tab like FQL where detailed analysis can be performed.

**Comment by nitishgoyal13** [comment]
Sunburst added as a tile
