### ISSUE TITLE
Create table raises an error "TABLE_INITIALIZATION_ERROR"

### ISSUE THREAD

**Issue by praveenjha527** [Flipkart/foxtrot#198]
I have setup foxtrot on my local machine using docker-compose file provided but i am getting an error while creating table with seggregatedBackend as true but when i am setting it to false the table is getting created.

Request Body:-

`{
    "name": "data1",
    "ttl": 7,
    "seggregatedBackend" : true
}`

Response Body:-
{
  "code": "TABLE_INITIALIZATION_ERROR",
  "message": "Create HBase Table - data1",
  "table": "data1"
}

**Comment by avanishp** [comment]
As the error states, you will first need to create the table in hbase

**Comment by praveenjha527** [comment]
@avanishp Working Now . Thanks
