### ISSUE TITLE
Order by clause not working with distinct key word

### ISSUE THREAD

**Issue by sanmishra7** [Flipkart/foxtrot#205]
select  distinct data.traceId from servicemonitor where temporal(_timestamp) between 1494354600000 and 1496082600000  order by header.timestamp desc limit 100

is supposed to give data in descending order of header.timestamp but it's not giving the intended results.

Whereas after dropping the distinct keyword, 
select data.traceId from servicemonitor where temporal(_timestamp) between 1494354600000 and 1496082600000 order by header.timestamp desc limit 100

It's giving desired results.

**Comment by nitishgoyal13** [comment]
This has been fixed in the latest release

**Comment by nitishgoyal13** [comment]
@santanusinha https://github.com/Flipkart/foxtrot/pull/238/files
