### ISSUE TITLE
limit keyword isn't working in FQL

### ISSUE THREAD

**Issue by sanmishra7** [Flipkart/foxtrot#206]
select distinct(data.traceId) from servicemonitor where temporal(_timestamp) between 1496687400000 and 1496773800000 limit 100
Here limit keyword is not working
It gave 3278659 traces

**Comment by nitishgoyal13** [comment]
Working fine
Tested it using 
select * from mercury where temporal(_timestamp) between 1536641051000 and 1536642051000 limit 1
