### ISSUE TITLE
Exclude large text fields from indexing in elasticsearch

### ISSUE THREAD

**Issue by r0goyal** [Flipkart/foxtrot#270]
Today there is no size limit on text field which allows users to put arbitrary amount of data in events. However this could to performance degradation and high memory/disk utilization if multiple events have large blobs.

**Comment by santanusinha** [comment]
The idea is to not index such huge fields on es. They will reside on hbase
and be available normally on queries etc.


The maxIndexableFielsSize value in config will govern this. We should keep
a default of max 512 bytes or something. Am open to discussion.

**Comment by santanusinha** [comment]
Done via #271
