### ISSUE TITLE
Do we need to create segregated tables manually in hbase?

### ISSUE THREAD

**Issue by Sreemanth** [Flipkart/foxtrot#44]
Created sample segregated table using create API.

***url:*** foxtrot/v1/tables

***Request:***
 ```json
    {
    "name" : "txseg",
    "ttl" : 180,
    "seggregatedBackend" : true                
    }
``` 

  Table not created in hbase automatically. 
  Created manually hbase table(txseg), then we are able to ingest data.

**Comment by r0goyal** [comment]
Yes, currently HBase tables are not automatically created or destroyed. This is being worked on.

**Comment by santanusinha** [comment]
This is partially a design decision, given the hbase tables act as raw data
store. Being able to delete the same would result in catastrophic loss of
data. Similarly, easy creation would mean a single typo would cause in
creation of useless tables on hbase.

**Comment by r0goyal** [comment]
@santanusinha In my opinion, at least a check for existence of HBase table if seggregatedBackend is true should be done and exception (Giving reason) should be thrown during table creation if table does not exists. This way there will no surprises after table is successfully created

**Comment by santanusinha** [comment]
That makes sense.. But don't allow hbase table management directly. Atleast
not if it's not under a flag.

**Comment by santanusinha** [comment]
Hi @Sreemanth are the answers satisfactory...? Can you close the issue then?

**Comment by santanusinha** [comment]
Check #58

**Comment by Sreemanth** [comment]
Thank you. @santanusinha  and  @r0goyal
