### ISSUE TITLE
Getting exception while initialization

### ISSUE THREAD

**Issue by shekhar-novo** [Flipkart/foxtrot#46]
Hi,
I have setup both elastic and Hbase. I'm getting following exception while running initialization java command. I'm using HBase version 1.1.2

5/11/02 14:06:57 INFO util.Version: HV000001: Hibernate Validator 4.3.1.Final
INFO  [2015-11-02 08:36:58,361] ElasticsearchConnection: Starting Elasticsearch Client
15/11/02 14:06:58 INFO elasticsearch.plugins: [Red Skull II] loaded [], sites []
INFO  [2015-11-02 08:36:59,187] ElasticsearchConnection: Added Elasticsearch Node : localhost
INFO  [2015-11-02 08:36:59,187] ElasticsearchConnection: Started Elasticsearch Client
INFO  [2015-11-02 08:36:59,194] InitializerCommand: # data nodes: 1, Setting replica count to: 0
ERROR [2015-11-02 08:36:59,227] InitializerCommand: Index consoles could not be created: [shekhar_01_dev][inet[/127.0.0.1:9300]][indices:admin/create]
ERROR [2015-11-02 08:36:59,238] InitializerCommand: Index table-meta could not be created: [shekhar_01_dev][inet[/127.0.0.1:9300]][indices:admin/create]
INFO  [2015-11-02 08:36:59,250] InitializerCommand: Create mapping: true
INFO  [2015-11-02 08:36:59,250] InitializerCommand: Creating hbase table
15/11/02 14:06:59 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-cdh4.2.0--1, built on 03/10/2014 23:10 GMT
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:host.name=172.16.7.90
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:java.version=1.8.0_60
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:java.class.path=foxtrot-server/target/foxtrot-server-0.1.jar
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:java.library.path=/Users/shekhargupta/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
INFO  [2015-11-02 08:36:59,758] org.apache.zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/var/folders/5_/spqzhsmn4zl7x_558nbz_2x40000gn/T/
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:os.name=Mac OS X
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:os.arch=x86_64
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:os.version=10.11
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:user.name=shekhargupta
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:user.home=/Users/shekhargupta
INFO  [2015-11-02 08:36:59,759] org.apache.zookeeper.ZooKeeper: Client environment:user.dir=/Users/shekhargupta/foxtrot/foxtrot
INFO  [2015-11-02 08:36:59,760] org.apache.zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=180000 watcher=hconnection
15/11/02 14:06:59 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 2688@Shekhars-MacBook-Pro.local
INFO  [2015-11-02 08:36:59,781] org.apache.zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
INFO  [2015-11-02 08:36:59,781] org.apache.zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
INFO  [2015-11-02 08:36:59,787] org.apache.zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x150c7555a390008, negotiated timeout = 40000
Exception in thread "main" java.lang.IllegalArgumentException: Not a host:port pair: PBUF

172.16.7.90����պ�*�}
	at org.apache.hadoop.hbase.util.Addressing.parseHostname(Addressing.java:60)
	at org.apache.hadoop.hbase.ServerName.<init>(ServerName.java:101)
	at org.apache.hadoop.hbase.ServerName.parseVersionedServerName(ServerName.java:283)
	at org.apache.hadoop.hbase.MasterAddressTracker.bytesToServerName(MasterAddressTracker.java:77)
	at org.apache.hadoop.hbase.MasterAddressTracker.getMasterAddress(MasterAddressTracker.java:61)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:667)
	at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:121)
	at com.flipkart.foxtrot.core.datastore.impl.hbase.HBaseUtil.createTable(HBaseUtil.java:72)
	at com.flipkart.foxtrot.server.InitializerCommand.run(InitializerCommand.java:146)
	at com.flipkart.foxtrot.server.InitializerCommand.run(InitializerCommand.java:36)
	at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58)
	at com.yammer.dropwizard.cli.Cli.run(Cli.java:53)
	at com.yammer.dropwizard.Service.run(Service.java:61)
	at com.flipkart.foxtrot.server.App.main(App.java:30)

**Comment by santanusinha** [comment]
Doesn't look like hbase is running properly. Check the HBase version in use.

Also, I see that it's not able to initialize the console's index. Please check ES index as well.

**Comment by shekhar82** [comment]
ES was working fine. Could you please let me know what version of HBase and ES should I use? I was having Hbase .94 and ES 1.7

**Comment by santanusinha** [comment]
The tested versions are:
HBase: 0.94.2-cdh4.2.0
ES: 1.7.3

Also, please use branch 0.3 instead of the master. This is where all the latest developments are happening.

It also has a docker compose to get you up and running quickly. We are yet to update the README. Follow the instructions in pull #89 

This version of HBase is a pain, we know, and we are in the process of upgrading it to the 1.x line. Should be done in 1-2 weeks max (probably earlier than that).

**Comment by santanusinha** [comment]
Closing this. Please reopen if you're still facing issues.
