### ISSUE TITLE
IndexMissingException while running queries

### ISSUE THREAD

**Issue by r0goyal** [Flipkart/foxtrot#53]
Suppose a table 'dummy' has ttl set to 3. Then normally it is supposed to have following 3 indexes -

foxtrot-dummy-table-19-11-2015
foxtrot-dummy-table-18-11-2015
foxtrot-dummy-table-17-11-2015

However, it is perfectly normal to not have events for some particular day. Today, if any of the index is not present, an IndexMissingException exception is thrown and query execution fails.

**Comment by santanusinha** [comment]
Fixed with #86
