### ISSUE TITLE
Split up table deletion

### ISSUE THREAD

**Issue by santanusinha** [Flipkart/foxtrot#67]
In case there are many indexes that match the deletion criteria due to whatever reason (loads of tables, wrong timestamp on incoming events) deletion fails and bloats up the cluster. This is a serious performance issue and can and will bring ES down.

**Comment by r0goyal** [comment]
@santanusinha Even today, deletion is done in batches of 5 indexes at a time and failure of one batch does not affect others. So I do not think this is an issue.

**Comment by santanusinha** [comment]
Ack..
