### ISSUE TITLE
Make caching more configurable

### ISSUE THREAD

**Issue by santanusinha** [Flipkart/foxtrot#79]
Right now, caching time is not configurable
Right now caching can't be turned off

This needs to change

**Comment by r0goyal** [comment]
@santanusinha Turning off caching can have severe performance impact on console. It will become very slow and also will lead to high pressure on query store as well. 

Time configurability is something which we should have.

**Comment by santanusinha** [comment]
Agreed. We need to make it time configurable atleast.

----
Upset the established order, and everything becomes chaos. I'm an agent of
chaos. Oh and you know the thing about chaos, it's fair.

**Comment by nitishgoyal13** [comment]
https://github.com/Flipkart/foxtrot/pull/241
