### ISSUE TITLE
Auto elasticsearch index optimization for older indices

### ISSUE THREAD

**Issue by r0goyal** [Flipkart/foxtrot#80]
Currently indices in elasticsearch remain on disk un-opmitized after last document is indexed. Since indices are time based, we know nothing will be indexed after due date (Except for few documents getting ingested later) and hence they can be optimized using elastic search optimize API for faster performance.

**Comment by vivekkothari** [comment]
Can we do this scheduled executor service and call the optimize API every day on ES indices suffixed with yesterday's date? Only problem with this approach is that in distributed environment all the nodes will call optimize API.

**Comment by r0goyal** [comment]
@vivekkothari Sorry for late reply. Yes, thinking of something on those lines itself. We need to figure out a way of electing a co-ordinator/admin node which can do run all these admin tasks.

**Comment by nitishgoyal13** [comment]
https://github.com/Flipkart/foxtrot/pull/241
